### PR TITLE
WIP: Client Generator

### PR DESCRIPTION
**Pull request by sciku1**
Soo I've got a bit of a mixed bag working here -- 
 - I managed to get it running with docker (which means no global dependency install) however not part of the dockerfile -- there was a large flaw in my thinking, you can only mount a volume when running, not when building, meaning you can't bring the files out of the docker container easily. 
 - The C# client is tied to .net 4.x... I don't think we want that. I can't even get it to compile then -- it gets a weird override method that shouldn't be. There's a dotnet core 2 version but it uses mono (which I also don't think we want). 
 - After tweaking the codegen a bit, I got the python client working well. Makes requests... what else can ya ask for? 😛 I haven't tried the nodejs one but I suspect it will work as well. 
 
 Thoughts? I will probably remove the csharp one but wanted to get some eyes first in case I'm missing anything obvious. Also, not sure how we wanna handle uploading to the respective package managers (pip, nuget, npm/yarn, maven, etc.)

### CODE REVIEW

**Comment by sciku1** [comment]
Addresses [#323](https://github.com/Universalis-FFXIV/Universalis/issues/323)

**Comment by karashiiro** [comment]
Is it possible for us to just generate the libraries in a Docker context and then not commit them? It'll bloat up the repo history if we commit hundreds of automatically-generated files. After generating the libraries, they can be released automatically from a GitHub Action, since there are preexisting scripts for that floating around in the Marketplace.

Not having a working C# client is unfortunate, but I can just manually create one after the rest of this is set up. Maintaining just one library is a lot more manageable than maintaining several.

**Comment by sciku1** [comment]
Oooohhh that's actually a great idea, I think NSwag supports autogenerating as well, which is *probably* better supported. Let me change this to work in a docker context (new pull request so this doesn't get added to the history when we merge). The only thing I'll continue to commit is the swagger.json file (maybe not even needed). 

As far as setting up the actual github workflow -- should I just commit the docker context and leave that to you @karashiiro ?

**Comment by karashiiro** [comment]
Yeah, so long as you detail the final output structure a bit, I should be able to figure out setting up the workflow with a bit of trial and error 👍

**Pull request closed without merging**
